# LibreLane configuration file

DESIGN_NAME: heichips25_template
#VHDL_FILES: 
#  - dir::../src/heichips25_template.vhdl
#  - dir::../src/tmds_encoder.vhdl
#  - dir::../src/TMDS_serializer.vhdl
#  - dir::../src/video.vhdl
#  - dir::../src/vtgen.vhdl
#  - dir::../src/shader.vhdl
#  - dir::../src/color_lut.vhdl
#  - dir::../src/gol_test.vhdl
  #- dir::../src/pix_Streacher.vhdl

VERILOG_FILES: 
  - dir::../sv/heichips25_template.sv
  - dir::../sv/divide_5.v
  - dir::../sv/tmds_encoder.v
  - dir::../sv/tmds_serializer.v
  - dir::../sv/video.sv
  - dir::../sv/vtgen_640_16_96_48_480_10_2_3.v
  - dir::../sv/shader.v
  - dir::../sv/color_lut.sv
  - dir::../sv/gol_test.sv
  - dir::../sv/pix_streacher.v
  - dir::../sv/pix_feeder.sv
CLOCK_PORT: clk
CLOCK_PERIOD: 10 # 10ns = 100MHz

# Reduce wasted space
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6

# Absolute die size
FP_SIZING: absolute

# Small DEF template
DIE_AREA: [0, 0, 500, 200]
FP_DEF_TEMPLATE: dir::def/heichips25_template_small_hdmi.def

# Large DEF template
#DIE_AREA: [0, 0, 500, 415]
#FP_DEF_TEMPLATE: dir::def/heichips25_template_large.def

# Don't use power rings or TopMetal2 layer
PDN_MULTILAYER: false
RT_MAX_LAYER: TopMetal1

# Enable for better SystemVerilog support
#USE_SLANG: true
