# LibreLane configuration file

DESIGN_NAME: heichips25_template
VHDL_FILES: 
  - dir::../src/heichips25_template.vhdl
  - dir::../src/tmds_encoder.vhdl
  - dir::../src/TMDS_serializer.vhdl
  - dir::../src/video.vhdl
  - dir::../src/vtgen.vhdl
  - dir::../src/shader.vhdl
  - dir::../src/color_lut.vhdl
  - dir::../src/gol_test.vhdl
  - dir::../src/pix_Streacher.vhdl
CLOCK_PORT: clk
CLOCK_PERIOD: 8 # 8ns = 125MHz

# Reduce wasted space
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6

# Absolute die size
FP_SIZING: absolute

# Small DEF template
DIE_AREA: [0, 0, 500, 200]
FP_DEF_TEMPLATE: dir::def/heichips25_template_small_hdmi.def

# Large DEF template
#DIE_AREA: [0, 0, 500, 415]
#FP_DEF_TEMPLATE: dir::def/heichips25_template_large.def

# Don't use power rings or TopMetal2 layer
PDN_MULTILAYER: false
RT_MAX_LAYER: TopMetal1

# Enable for better SystemVerilog support
#USE_SLANG: true
