// Auto-generated by LibreLane
module heichips25_bagel(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst_n,
  input ena,
  input[7:0] ui_in,
  input[7:0] uio_in,
  output[7:0] uo_out,
  output[7:0] uio_out,
  output[7:0] uio_oe,
  output tmds_b,
  output tmds_g,
  output tmds_r,
  output tmds_clk
);
endmodule
